---
title: "linear models"
output: github_document
---


```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

# do some data cleaning
```{r}
data('nyc_airbnb')

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |> 
  filter(borough != "Staten Island") |> 
  select(price, stars, borough, neighborhood, room_type)
```

```{r}
fit = lm(price ~ stars, data = nyc_airbnb)
summary(fit)
names(summary(fit))
coef(fit)
broom::tidy(fit)
fit|>
  broom::glance()
```

more complex:
```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
broom::tidy(fit)|>
  select(term, estimate, p.value) |> 
  mutate(term = str_replace(term, "borough", "Borough: ")) |> 
  knitr::kable(digits = 3)
```
```{r}
nyc_airbnb = 
  nyc_airbnb |> 
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type))

```

# some diagnostics

```{r}
modelr::add_residuals(nyc_airbnb, fit)|>
  ggplot(aes(x = borough, y = resid)) + geom_violin()+
  ylim(-200,500)
```
```{r}
nyc_airbnb|>
modelr::add_residuals(fit)|>
modelr::add_predictions(fit)|>
  ggplot(aes(x = pred, y = resid)) + geom_point()
```

```{r}
nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = stars, y = resid)) + geom_point()+
  stat_smooth(method = 'lm')
```

residuals against stars:
```{r}
modelr::add_residuals(nyc_airbnb, fit)|>
  ggplot(aes(x = stars, y = resid)) + geom_point()
```

# hypothesis testing

```{r}
fit|>
  broom::tidy()
```

```{r}
fit_null = lm(price ~ stars + borough, data = nyc_airbnb)
fit_alt = lm(price ~ stars + borough + room_type, data = nyc_airbnb)
```

```{r}
fit_null|>
  broom::tidy()
fit_alt|>
  broom::tidy()
```
```{r}
anova(fit_null, fit_alt) |> 
  broom::tidy()
```

```{r}
nyc_airbnb |> 
  lm(price ~ stars * borough + room_type * borough, data = _) |> 
  broom::tidy() |> 
  knitr::kable(digits = 3)
```

fit separate models

```{r}
nyc_airbnb |> 
  filter(borough == 'Manhattan')|>
  lm(price ~ stars + room_type, data = _) |> 
  broom::tidy() |> 
  knitr::kable(digits = 3)
```

```{r}
nest_lm_res =
  nyc_airbnb |> 
  nest(data = -borough) |> 
  mutate(
    models = map(data, \(df) lm(price ~ stars + room_type, data = df)),
    results = map(models, broom::tidy)) |> 
  select(-data, -models) |> 
  unnest(results)
```

```{r}
nest_lm_res |> 
  select(borough, term, estimate) |> 
  mutate(term = fct_inorder(term)) |> 
  pivot_wider(
    names_from = term, values_from = estimate) |> 
  knitr::kable(digits = 3)
```

```{r}
nyc_airbnb|>
  filter(
    borough == 'Manhattan',
    neighborhood == 'Chinatown'
  )|>
  lm(price ~ stars + room_type, data = _)|>
  broom::tidy()
```

for all neighborhood:
```{r}
manhattan_neighborhood_fit_df = 
nyc_airbnb|>
  filter(
    borough == 'Manhattan'
  )|>
  nest(data = -(borough:neighborhood))|>
  mutate(
    models = map(data, \(df) lm(price ~ stars + room_type, data = df)),
    results = map(models, broom::tidy))|>
  select(-data, -models) |> 
  unnest(results)
```

look at the effect of room type

```{r}
manhattan_neighborhood_fit_df|>
  filter(str_detect(term, "room_type")) |> 
  ggplot(aes(x = neighborhood, y = estimate)) + 
  geom_point() + 
  facet_wrap(~term) + 
  theme(axis.text.x = element_text(angle = 80, hjust = 1))
```
```{r}
manhattan_neighborhood_fit_df|>
  filter(str_detect(term, "room_type")) |> 
  ggplot(aes(x = term, y = estimate)) + 
  geom_point() + 
  geom_boxplot()
```




